### PR TITLE
Add quick doc on planet

### PR DESCRIPTION
**Pull request by mscherer**

### CODE REVIEW

**Comment by mscherer** [comment]
So I tried to be concise, and avoid duplicating existing doc, but maybe I missed some stuff (as I kinda do the same stuff everywhere, I am fully unable to see what is no longer obvious and/or unclear)

**Comment by nigelbabu** [comment]
This works for now. I'll try to add my blog at some point and if I notice something missing, I'll add a pull request.

**Comment by mscherer** [comment]
Also, should we use the infra-docs to encode the process for adding someone to the planet ?

**Comment by nigelbabu** [comment]
I'm unsure. But it would be good to add it. Better to have it than not have it.

**Pull request merged**
